version: '3'

services:
  chatapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash -c "
      uvicorn app.main:app 
      --host 0.0.0.0 
      --port 9000 
      --reload"
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - mongochatapp

  mongochatapp:
    image: mongo:latest
    container_name: mongochatapp
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - mongochatapp:/data/db
      - ./db:/data/db:rw
    ports:
      - "27018:27017"

volumes:
  mongochatapp:
    driver: local
