version: "3"
services:

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - sharetrip-network
      - chatapp-network
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true
  
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    expose:
    - "8000"
    networks:
      - sharetrip-network
    volumes:
      - ./backend:/app
    environment:
      - CLIENT=http://localhost:3000
    depends_on:
      - mongo
    command: bash -c "
      uvicorn app.main:app 
      --host 0.0.0.0 
      --port 8000 
      --reload"

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - sharetrip-network
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - mongo:/data/db
      - ./backend/db:/data/db:rw
    ports:
      - "27017:27017"
  
  chatapp:
    build:
      context: ./shareTripChatApp
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 9000:9000
    expose:
    - "9000"
    networks:
      - chatapp-network
    volumes:
      - ./shareTripChatApp:/usr/app
    environment:
      - CLIENT=http://localhost:3000
    depends_on:
      - mongochatapp

  mongochatapp:
    image: mongo:latest
    container_name: mongochatapp
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME_CHATAPP}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD_CHATAPP}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE_CHATAPP}
    networks:
      - chatapp-network
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - mongochatapp:/data/db
      - ./shareTripChatApp/db:/data/db:rw
    ports:
      - "27018:27017"


networks:
  sharetrip-network:
    driver: bridge
  chatapp-network:
    driver: bridge

volumes:
  mongo:
    driver: local
  mongochatapp:
    driver: local