version: '3'

services:
  backend:
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn app.main:app 
      --host 0.0.0.0 --port 8000 
      --reload      
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - mongo:/data/db
      - ./db:/data/db:rw
    ports:
      - "27017:27017"

volumes:
  mongo:
    driver: local
