version: '3'

services:
  chatapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo_node

  mongo_node:
    image: mongo:latest
    container_name: mongo_node
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - mongo:/data/db
      - ./db:/data/db:rw
    ports:
      - "27017:27017"

volumes:
  mongo:
    driver: local
